World: world

Team:
  spawn:
    1:
      x: 6
      y: -4
      z: 98
    2:
      x: 6
      y: -3
      z: -81

Core:
  1:
    x: 6
    y: -24
    z: 95
  2:
    x: 6
    y: -23
    z: -81
  Health: 100

Generator:
  1:
    x: 0
    y: 59
    z: 0
  2:
    x: 1
    y: 59
    z: 1

PrepareTime: 60

Border:
  +X: 54
  -X: -42
  +Z: 21
  -Z: -12
  +y: -2
  -y: -53